[package]
edition = "2024"
name = "audit-check-test"
rust-version = "1.85.0"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anymap = "0.12.1"
aovec = "1.1.0"
